### ISSUE TITLE
Should expand relative paths in Pester path properties

### ISSUE THREAD

**Issue by johlju** [dsccommunity/DscResource.Test#121]
If the property `OutputPath` is used in the build.yaml with a relative path (to the project path), it will not be made an absolute path by the task, meaning in this case, the test result file end up in the wrong place.

```
DscTest:
  Pester:
    Configuration:
      TestResult:
        OutputPath: ./output/testResults/NUnitXml_HQRM_Tests.xml
```

The variable `$DscTestOutputFolder` is set to the absolute path of the projects './output/testResults' folder here:

https://github.com/dsccommunity/DscResource.Test/blob/27c70ec121b41eff95f17747f0dc2176f89cdfa8/source/tasks/Invoke_HQRM_Tests.build.ps1#L90-L93

So here for each property that is a path, e.g. `OutputPath`, should be checked whether it is an absolute path. If not, join the relative path with the path in the variable above.

https://github.com/dsccommunity/DscResource.Test/blob/27c70ec121b41eff95f17747f0dc2176f89cdfa8/source/tasks/Invoke_HQRM_Tests.build.ps1#L240
